### ISSUE TITLE
Database Groups Infinite Loop Crash

### ISSUE THREAD

**Issue by Davnit** [stealthbot/StealthBot#36]
If you create 2 groups 'a' and 'b' in the database manager and assign them to each other (a is a member of b and b is a member of a) the program crashes to desktop.

http://i.imgur.com/7qFKYm9.png

I can only assume that doing this via command or by manually editing the database file would cause similar problems.

**Comment by Davnit** [comment]
Trying to do this in a command doesn't work, but produces confusing output.

> /set b --type group --group a
> Error: "a" is already a member of group "b."

It's not clear if its trying to re-assign a to b or if its saying you can't assign b to a because of this condition. This would be a separate issue.

**Comment by nmbook** [comment]
The DB Manager portion should no longer be allowed as of c2787ca2dcb44e295e456ed7d9158c1673dbc85a.

It doesn't allow you to select children or children's children (any depth because it uses `Node.IsParentOf()`) in the group list now.

This doesn't really stop the other bugs, i.e. with .add/.set and the DB at large.

**Comment by Davnit** [comment]
Where else have we verified that this occurs? I don't think you can do it with /add but I have not tried manually editing the database file.

**Comment by nmbook** [comment]
Oh, okay, if this issue is just about the crash, then that's fixed. It was only occuring because of the actual TreeView objects anyway. I haven't encountered another crash. Your previous comment lists another problem (different issue, as stated).
