### ISSUE TITLE
ActiveX Files error

### ISSUE THREAD

**Issue by iCCupPlatoon** [stealthbot/StealthBot#53]
Greetings.
When I try to compile a project, I get errors (" could not be loaded) and (Method or data member not found.) I understand that the reason in ActiveX components: Could you tell me how to configure the project for correct compilation?

Windows 8.1 x64

**Comment by iCCupPlatoon** [comment]
@stealthbot hey?

**Comment by Davnit** [comment]
Sorry all of the work I've done has been on a Windows 7 VM. I had to use a special installer to get Visual Studio to work (see [this](https://github.com/martinmoene/martin-moene.blogspot.com/tree/master/How%20to%20install%20Visual%20Studio%206%20on%20Windows%208.1)).

Since it sounds like things are somewhat working for you... I would try running Visual Studio in compatibility mode for Vista SP2 and/or as admin. You may also have to install StealthBot using one of the existing installers for the dependencies to be registered. Make sure the -addpath command line arg is set to the install location.

The only other thing I do is launch VS and then open the project through it rather than opening the project directly. I'm just throwing out ideas and things I've had to do before. I don't really have a direct answer.

**Comment by iCCupPlatoon** [comment]
Nothing, everything is in order. Of course, I can not compile the project, but I can open the project files separately. This allows me to [transfer the functionality from VB6 to VB.NET](http://www.stealthbot.net/forum/index.php?/topic/7870-transfer-to-the-vb-net-platform/) stably. I can see the parameters of forms, trace the dependencies of functions, find their declarations - this is enough for me.
