### ISSUE TITLE
Format not understood. Error retrieving news from http://www.stealthbot.net.

### ISSUE THREAD

**Issue by SpeciaLisT24** [stealthbot/StealthBot#89]
Hello. I installed stealthbot the other day and everything seemed to work fine. Got online and it worked. However, a day later it started coming up with this error
Format not understood. Error retrieving news from http://www.stealthbot.net.

Now... This is how far the bot progresses without moving any further or even timing out with an error message.
[18:36:06] Connecting your bot...
 [18:36:06] [BNLS] Connecting to the BNLS server at jbls.davnit.net...
 [18:36:06] [BNLS] Connected!
 [18:36:06] [BNLS] Authorized!
 [18:36:06] [BNCS] Connecting to the Battle.net server at uswest.battle.net...
 [18:36:06] [BNCS] Connected to 54.68.223.127!
 [18:36:07] [BNCS] Checking version...
 
The CD key has worked, and i have multiple CD keys, all Diablo 2 (regular not expansion).
My suspicion is that my virus protector on my computer did something, but i did follow the exclusion guide for the stealthbot release under 493. I've done fresh installs - while also deleting my profile thru appdata in my :C: drive in Users. ( Multiple times) And now I'm fresh out of solutions.

Thanks for reading. Appreciate the help.
-Spec

**Comment by Davnit** [comment]
The news isn't very important so that error can be ignored, and it's unrelated to anything else.

When the bot gets stuck on "Checking version..." this usually indicates a temporary IP restriction from the Battle.net server. There's not much we can do about that and no way to know why it happened or how long it'll last. Trying to reconnect while IP banned typically only makes it longer. You'll just have to change your public IP address, use a proxy, or wait it out. Sorry.

**Comment by SpeciaLisT24** [comment]
Thanks. No that makes sense actually. I found my bot trying to reconnect multiple times, and that might be the reason why. Thanks for the response Davnit.
