### ISSUE TITLE
IpBan Stealthbot

### ISSUE THREAD

**Issue by SpeciaLisT24** [stealthbot/StealthBot#90]
Does anyone know the duration of a typical ipban? The scenario is a bot trying to reconnect instantly for maybe 50 times in a row, unsuccessfully.

How long would this ipban last?

Does it extend the timer everytime you try to log in lets say every couple of hours?

Is there something I can do besides changing my dynamic IP for my modem to get it online?

(I have disabled the reconnection feature to make sure this doesn't happen again).

Thanks again for your time and I hope you guys have a great weekend.

-Spec

**Comment by Davnit** [comment]
Answering this 6 months later, just for reference...

> Does anyone know the duration of a typical ipban? The scenario is a bot trying to reconnect instantly for maybe 50 times in a row, unsuccessfully.

I'm not super familiar with the current timings but a lot of it will hinge on the reason for the disconnects.

> Does it extend the timer everytime you try to log in lets say every couple of hours?

If the current ban hasn't yet been lifted, and you try to connect, the timer is extended. Most bans I've encountered don't last for multiple hours though. A good strategy is to use an [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff).

> Is there something I can do besides changing my dynamic IP for my modem to get it online?

You could use a proxy, otherwise no.
